"use client";
import Link from 'next/link';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
export default function MenuBookViewer({menu,total}:{menu:'lunch'|'dinner',total:number}){
 const[page,setPage]=useState(2),[single,setSingle]=useState(false),[turn,setTurn]=useState<null|{from:number,to:number,dir:number}>(null),[zoomPage,setZoomPage]=useState(2);
 const touch=useRef<{x:number,y:number}|null>(null),busy=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),pageRef=useRef(2);
 const step=single?1:2;const title=menu==='lunch'?'Lunch Menu':'Dinner Menu';const source=(n:number)=>`/menus/${menu}/page-${String(n).padStart(2,'0')}.jpg`;
 useEffect(()=>{const mq=window.matchMedia('(max-width: 640px)');const sync=()=>{setSingle(mq.matches)};sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 const go=useCallback((target:number)=>{if(busy.current||target<1||target>total||target===pageRef.current)return false;const from=pageRef.current;busy.current=true;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;setTurn({from,to:target,dir:target>from?1:-1});timer.current=setTimeout(()=>{pageRef.current=target;setPage(target);setTurn(null);busy.current=false},reduced?0:650);return true},[total]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[role="dialog"]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(Math.min(total,pageRef.current+step))}if(e.key==='ArrowLeft'){e.preventDefault();go(Math.max(1,pageRef.current-step))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[go,step,total]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:ModelContext}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'navigate_menu_page',description:`Open a page of the BiBiChik ${menu} menu in the visible book reader.`,inputSchema:{type:'object',properties:{page:{type:'integer',minimum:1,maximum:total}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const n=(input as {page?:unknown})?.page;if(typeof n!=='number'||!Number.isInteger(n)||n<1||n>total)throw new Error(`Page must be an integer from 1 to ${total}.`);if(busy.current)throw new Error('A page is turning. Please try again.');if(n!==pageRef.current){go(n);await new Promise(r=>setTimeout(r,700))}return{menu,page:pageRef.current,total}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[go,menu,total]);
 const shown=turn?turn.to:page;
 const end=Math.min(total,page+(single?0:1));
 return <section className="reader-table"><div className="container"><div className="reader-title"><Link href="/menu" className="text-link">← Back to menu</Link><h1>{title}</h1><a href={`/menus/${menu}.pdf`} target="_blank" rel="noopener noreferrer" className="text-link">Original PDF ↗</a></div><p className="reader-hint">{single?'Swipe to turn the page. Tap “Read page” for a closer look.':'Click a page or use the arrow keys to turn.'}</p><div className={`open-book ${single?'single':''}`} aria-label={`${title}, pages ${page} to ${end}`} onTouchStart={e=>touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy))go(Math.max(1,Math.min(total,page+(dx<0?step:-step))))}}>
  {Array.from({length:single?1:2},(_,i)=>{const n=shown+i;return <button key={i} className="paper-page" disabled={!!turn||(i===0&&!single?page===1:page+step>total)} onClick={()=>go(Math.max(1,Math.min(total,page+(i===0&&!single?-step:step))))} aria-label={i===0&&!single?'Previous pages':'Next pages'}>{n<=total?<img src={source(n)} alt={`${title}, original PDF page ${n}`} draggable={false}/>:<div className="endpaper"><img src="/assets/emblem.png" alt="BiBiChik"/><span>A Taste of Nyonya Heritage</span></div>}</button>})}
  {turn&&<div aria-hidden="true" className={`turning-page ${turn.dir>0?'forward':'backward'}`}><img src={source(turn.from+(turn.dir>0&&!single?1:0))} alt=""/></div>}
 </div><div className="reader-controls"><button className="text-link" onClick={()=>go(Math.max(1,page-step))} disabled={page===1||!!turn}>← Previous</button><span aria-live="polite">Page {page}{end>page?`–${end}`:''} / {total}</span><button className="text-link" onClick={()=>go(Math.min(total,page+step))} disabled={page+step>total||!!turn}>Next →</button></div><div className="reader-secondary"><Dialog><DialogTrigger className="text-link" onClick={()=>setZoomPage(page)}>Read page {page} ↗</DialogTrigger><DialogContent className="page-dialog"><DialogTitle>{title} · Page {zoomPage}</DialogTitle><DialogDescription>Original menu page. Scroll to read the full page.</DialogDescription><img src={source(zoomPage)} alt={`${title}, page ${zoomPage} in full detail`}/><div className="zoom-controls"><button className="button secondary" disabled={zoomPage===1} onClick={()=>setZoomPage(n=>n-1)}>Previous</button><button className="button secondary" disabled={zoomPage===total} onClick={()=>setZoomPage(n=>n+1)}>Next</button></div></DialogContent></Dialog><Link className="text-link" href={`/menu/${menu==='lunch'?'dinner':'lunch'}`}>View {menu==='lunch'?'dinner':'lunch'} menu →</Link></div></div></section>
}
