"use client";
import Link from 'next/link';
import {copy,pathFor,type Locale} from '@/lib/i18n';
import {useCallback,useEffect,useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
type ModelContext={registerTool:(tool:{name:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>Promise<unknown>},options:{signal:AbortSignal})=>void|Promise<void>};
const TURN_MS=620;
export default function MenuBookViewer({menu,total,locale='en'}:{menu:'lunch'|'dinner',total:number,locale?:Locale}){
 const c=copy[locale].menu;
 const[page,setPage]=useState(2),[single,setSingle]=useState(false),[turn,setTurn]=useState<null|{from:number,to:number,dir:number}>(null),[zoomPage,setZoomPage]=useState(2);
 const touch=useRef<{x:number,y:number}|null>(null),dragPage=useRef<HTMLButtonElement|null>(null),ignoreClickUntil=useRef(0),busy=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null),pageRef=useRef(2),turnTarget=useRef<number|null>(null);
 const step=single?1:2;const title=menu==='lunch'?c.lunch:c.dinner;const source=(n:number)=>`/menus/${menu}/page-${String(n).padStart(2,'0')}.jpg`;
 useEffect(()=>{const mq=window.matchMedia('(max-width: 640px)');const sync=()=>{setSingle(mq.matches)};sync();mq.addEventListener('change',sync);return()=>mq.removeEventListener('change',sync)},[]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current)},[]);
 useEffect(()=>{for(const n of [page-step,page-step+1,page+step,page+step+1])if(n>=1&&n<=total){const image=new window.Image();image.src=source(n)}},[menu,page,step,total]);
 const finishTurn=useCallback(()=>{const target=turnTarget.current;if(target===null)return;if(timer.current)clearTimeout(timer.current);turnTarget.current=null;pageRef.current=target;setPage(target);setTurn(null);busy.current=false},[]);
 const go=useCallback((target:number)=>{if(busy.current||target<1||target>total||target===pageRef.current)return false;const from=pageRef.current;busy.current=true;turnTarget.current=target;const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;setTurn({from,to:target,dir:target>from?1:-1});timer.current=setTimeout(finishTurn,reduced?0:TURN_MS+80);return true},[finishTurn,total]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,textarea,select,[role="dialog"]'))return;if(e.key==='ArrowRight'){e.preventDefault();go(Math.min(total,pageRef.current+step))}if(e.key==='ArrowLeft'){e.preventDefault();go(Math.max(1,pageRef.current-step))}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[go,step,total]);
 useEffect(()=>{const ctx=(document as Document&{modelContext?:ModelContext}).modelContext;if(!ctx?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(ctx.registerTool({name:'navigate_menu_page',description:`Open a page of the BiBiChik ${menu} menu in the visible book reader.`,inputSchema:{type:'object',properties:{page:{type:'integer',minimum:1,maximum:total}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},async execute(input){const n=(input as {page?:unknown})?.page;if(typeof n!=='number'||!Number.isInteger(n)||n<1||n>total)throw new Error(`Page must be an integer from 1 to ${total}.`);if(busy.current)throw new Error('A page is turning. Please try again.');if(n!==pageRef.current){go(n);await new Promise(r=>setTimeout(r,TURN_MS+80))}return{menu,page:pageRef.current,total}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}return()=>lifecycle.abort()},[go,menu,total]);
 const shown=turn?turn.to:page;
 const end=Math.min(total,page+(single?0:1));
 return <section className="reader-table"><div className="container"><div className="reader-title"><Link href={pathFor(locale,'/menu')} className="text-link">← {c.back}</Link><h1>{title}</h1><a href={`/menus/${menu}.pdf`} target="_blank" rel="noopener noreferrer" className="text-link">{c.original} ↗</a></div><p className="reader-hint">{single?c.swipe:c.click}</p><div className={`open-book ${single?'single':''}`} aria-label={`${title}, pages ${page} to ${end}`} onTouchStart={e=>{if(!busy.current)touch.current={x:e.touches[0].clientX,y:e.touches[0].clientY}}} onTouchMove={e=>{if(!single||!touch.current||busy.current)return;const dx=e.touches[0].clientX-touch.current.x,dy=e.touches[0].clientY-touch.current.y;if(Math.abs(dx)<8||Math.abs(dx)<Math.abs(dy)*1.15)return;const el=dragPage.current;if(el){el.classList.add('dragging');el.style.transform=`translateX(${Math.max(-7,Math.min(7,dx*.1))}px) rotateY(${Math.max(-5,Math.min(5,dx*.08))}deg)`}}} onTouchEnd={e=>{if(!touch.current)return;const dx=e.changedTouches[0].clientX-touch.current.x,dy=e.changedTouches[0].clientY-touch.current.y;touch.current=null;const el=dragPage.current;if(el){el.classList.remove('dragging');el.style.transform=''}if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy))ignoreClickUntil.current=performance.now()+400;if(Math.abs(dx)>=55&&Math.abs(dx)>Math.abs(dy)*1.15)go(Math.max(1,Math.min(total,pageRef.current+(dx<0?step:-step))))}} onTouchCancel={()=>{touch.current=null;const el=dragPage.current;if(el){el.classList.remove('dragging');el.style.transform=''}}}>
  {Array.from({length:single?1:2},(_,i)=>{const n=shown+i;return <button key={i} ref={i===0?dragPage:undefined} className="paper-page" disabled={!!turn||(i===0&&!single?page===1:page+step>total)} onClick={()=>{if(performance.now()<ignoreClickUntil.current)return;go(Math.max(1,Math.min(total,pageRef.current+(i===0&&!single?-step:step))))}} aria-label={i===0&&!single?c.previous:c.next}>{n<=total?<img src={source(n)} alt={`${title}, original PDF page ${n}`} draggable={false}/>:<div className="endpaper"><img src="/assets/emblem.png" alt="BiBiChik"/><span>{c.endpaper}</span></div>}</button>})}
  {turn&&<>{!single&&<div aria-hidden="true" className={`turning-stationary ${turn.dir>0?'left':'right'}`}>{turn.from+(turn.dir<0?1:0)<=total?<img src={source(turn.from+(turn.dir<0?1:0))} alt=""/>:<div className="endpaper"><img src="/assets/emblem.png" alt=""/><span>{c.endpaper}</span></div>}</div>}<div aria-hidden="true" className={`turning-page ${turn.dir>0?'forward':'backward'}`} onAnimationEnd={e=>{if(e.target===e.currentTarget)finishTurn()}}><div className="turning-face front"><img src={source(turn.from+(turn.dir>0&&!single?1:0))} alt=""/></div><div className="turning-face back"><img src={source(turn.to+(turn.dir<0&&!single?1:0))} alt=""/></div></div></>}
 </div><div className="reader-controls"><button className="text-link" onClick={()=>go(Math.max(1,page-step))} disabled={page===1||!!turn} >← {c.previous}</button><span aria-live="polite">{c.page} {page}{end>page?`–${end}`:''} / {total}</span><button className="text-link" onClick={()=>go(Math.min(total,page+step))} disabled={page+step>total||!!turn}>{c.next} →</button></div><div className="reader-secondary"><Dialog><DialogTrigger className="text-link" onClick={()=>setZoomPage(page)}>{c.read.replace('{page}',String(page))} ↗</DialogTrigger><DialogContent className="page-dialog"><DialogTitle>{title} · {c.page} {zoomPage}</DialogTitle><DialogDescription>{c.dialog}</DialogDescription><img src={source(zoomPage)} alt={`${title}, page ${zoomPage} in full detail`}/><div className="zoom-controls"><button className="button secondary" disabled={zoomPage===1} onClick={()=>setZoomPage(n=>n-1)}>{c.previous}</button><button className="button secondary" disabled={zoomPage===total} onClick={()=>setZoomPage(n=>n+1)}>{c.next}</button></div></DialogContent></Dialog><Link className="text-link" href={pathFor(locale,`/menu/${menu==='lunch'?'dinner':'lunch'}`)}>{c.view.replace('{menu}',locale==='en'?(menu==='lunch'?'dinner menu':'lunch menu'):menu==='lunch'?c.dinner:c.lunch)} →</Link></div></div></section>
}
