"use client";
import Link from 'next/link';
import Image from 'next/image';
import {usePathname} from 'next/navigation';
import {useEffect,useState,type ReactNode} from 'react';
import {Menu} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
import {copy,localeFromPath,pathFor,type Locale} from '@/lib/i18n';

const navPaths=['/','/our-story','/menu','/our-flavours'] as const;
export function Header(){const path=usePathname(),locale=localeFromPath(path),c=copy[locale];const[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(window.scrollY>20);f();window.addEventListener('scroll',f,{passive:true});return()=>window.removeEventListener('scroll',f)},[]);const base=locale==='zh'?path.replace(/^\/zh(?=\/|$)/,'')||'/':path;const languageLinks=<span className="language-switch"><Link href={pathFor('en',base)} lang="en" aria-current={locale==='en'?'page':undefined}>EN</Link><span aria-hidden="true">|</span><Link href={pathFor('zh',base)} lang="zh-CN" aria-current={locale==='zh'?'page':undefined}>中文</Link></span>;return <header className={`site-header ${scrolled?'scrolled':''}`}><div className="header-inner"><Link className="brand" href={pathFor(locale,'/')} aria-label={`BiBiChik ${c.nav.home}`}><img src="/assets/logo.png" alt={`BiBiChik — ${c.home.title.replaceAll("|"," ")}`}/></Link><nav className="desktop-nav" aria-label={c.nav.main}>{navPaths.map((h,i)=><Link href={pathFor(locale,h)} key={h} aria-current={(h==='/'?base===h:base.startsWith(h))?'page':undefined}>{[c.nav.home,c.nav.story,c.nav.menu,c.nav.flavours][i]}</Link>)}</nav><div className="desktop-language">{languageLinks}</div><Button href={pathFor(locale,'/visit-us')} className="visit-cta">{c.nav.visit}</Button><Sheet><SheetTrigger className="mobile-toggle" aria-label={c.nav.open}><Menu/></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle>BiBiChik</SheetTitle><SheetDescription>{c.home.title.replaceAll("|"," ")}</SheetDescription><nav aria-label={c.nav.mobile}>{navPaths.map((h,i)=><SheetClose asChild key={h}><Link href={pathFor(locale,h)}>{[c.nav.home,c.nav.story,c.nav.menu,c.nav.flavours][i]}</Link></SheetClose>)}<SheetClose asChild><Link href={pathFor(locale,'/visit-us')}>{c.nav.visit}</Link></SheetClose><div className="mobile-language"><span className="language-switch"><SheetClose asChild><Link href={pathFor("en",base)} lang="en" aria-current={locale==="en"?"page":undefined}>EN</Link></SheetClose><span aria-hidden="true">|</span><SheetClose asChild><Link href={pathFor("zh",base)} lang="zh-CN" aria-current={locale==="zh"?"page":undefined}>中文</Link></SheetClose></span></div></nav></SheetContent></Sheet></div></header>}
export function Button({href,children,secondary=false,className=''}:{href:string,children:ReactNode,secondary?:boolean,className?:string}){return <Link className={`button ${secondary?'secondary':''} ${className}`} href={href}>{children}</Link>}
export function Motif({className=''}:{className?:string}){return <img className={`motif ${className}`} src="/assets/emblem.png" alt="" aria-hidden="true"/>}
export function Hero({title,subtitle,description,image,alt,children}:{title:ReactNode,subtitle:string,description?:string,image:string,alt:string,children?:ReactNode}){return <section className={`hero hero-${image}`}><div className="hero-copy"><h1>{title}</h1><p className="hero-subtitle">{subtitle}</p>{description&&<p className="hero-description">{description}</p>}{children}</div><div className="hero-photo"><Image src={`/assets/${image}.webp`} alt={alt} width={1600} height={1100} sizes="100vw" priority/></div></section>}
const categoryImages=['classics','noodles','small-plates','dessert','drinks'];
export function MenuPreview({locale='en'}:{locale?:Locale}){const c=copy[locale];return <section className="mint section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{c.preview.eyebrow}</p><h2>{c.preview.title}</h2></div><Link className="text-link" href={pathFor(locale,'/menu')}>{c.preview.view} <span>→</span></Link></div><div className="category-grid">{c.preview.categories.map(([name,body],i)=><Link href={pathFor(locale,'/menu')} key={name} className="category"><Image src={`/assets/${categoryImages[i]}.webp`} alt={name} width={1254} height={1254} sizes="(max-width: 800px) 50vw, 25vw"/><h3>{name}</h3><p>{body}</p></Link>)}</div></div></section>}
export type Location={name:string,address:string,phone:string,mapUrl:string,image:string,openingHours?:{day:string,sessions:string[]}[]};
export const locations:Location[]=[
  {name:'BiBiChik Sunway 163 Mall',address:'LG1-11 & 12, Sunway 163 Mall, 8, Jalan Kiara, Mont Kiara, 50480 Kuala Lumpur, Wilayah Persekutuan Kuala Lumpur',phone:'011-6214 7497',mapUrl:'https://www.google.com/maps/search/?api=1&query=BiBiChik%20Sunway%20163%20Mall',image:'/assets/location-one.webp',openingHours:[
    {day:'Monday',sessions:['10 am–10:30 pm']},{day:'Tuesday',sessions:['10 am–10:30 pm']},{day:'Wednesday',sessions:['10 am–10:30 pm']},{day:'Thursday',sessions:['10 am–10:30 pm']},{day:'Friday',sessions:['10 am–10:30 pm']},{day:'Saturday',sessions:['10 am–10:30 pm']},{day:'Sunday',sessions:['10 am–10:30 pm']}
  ]},
  {name:'BiBiChik SS2',address:'No. 17, Jalan SS 2/30, SS 2, 47300 Petaling Jaya, Selangor',phone:'011-7023 3354',mapUrl:'https://www.google.com/maps/search/?api=1&query=BiBiChik%20SS2%20Petaling%20Jaya',image:'/assets/location-two.webp',openingHours:[
    {day:'Monday',sessions:['11 am–3 pm','5:30–10:30 pm']},{day:'Tuesday',sessions:[]},{day:'Wednesday',sessions:['11 am–3 pm','5:30–10:30 pm']},{day:'Thursday',sessions:['11 am–3 pm','5:30–10:30 pm']},{day:'Friday',sessions:['11 am–3 pm','5:30–10:30 pm']},{day:'Saturday',sessions:['11 am–3 pm','5:30–10:30 pm']},{day:'Sunday',sessions:['11 am–3 pm','5:30–10:30 pm']}
  ]}
];
export function Locations({compact=false,locale='en'}:{compact?:boolean,locale?:Locale}){const c=copy[locale];return <section className="blue section" id="locations"><div className="container"><div className="section-heading"><div><p className="eyebrow">{c.common.locations}</p><h2>{c.common.find}</h2></div><p>{compact||locale==='en'?c.common.welcome:c.visit.locationBody}</p></div><div className="location-grid">{locations.map(l=><article className="location-card" key={l.name}><Image src={l.image} alt={c.alt.interior} width={1570} height={710} sizes="(max-width: 800px) 100vw, 50vw"/><div><h3>{l.name}</h3><p>{l.address}</p><p><a href={`tel:+60${l.phone.replace(/\D/g,'').slice(1)}`}>{l.phone}</a></p>{l.openingHours&&<div className="location-hours"><h4>{c.common.hours}</h4><dl>{l.openingHours.map(({day,sessions})=><div key={day}><dt>{c.days[['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].indexOf(day)]}</dt><dd>{sessions.length?sessions.map(time=><span key={time}>{time}</span>):c.common.closed}</dd></div>)}</dl></div>}<a className="button secondary" href={l.mapUrl} target="_blank" rel="noopener noreferrer">{c.common.directions}</a></div></article>)}</div></div></section>}
export function Footer(){const path=usePathname(),locale=localeFromPath(path),c=copy[locale];return <footer><div className="container footer-grid"><Link href={pathFor(locale,'/')} className="brand"><img src="/assets/logo.png" alt={`BiBiChik — ${c.home.title.replaceAll("|"," ")}`}/></Link><div><h4>{c.common.locations}</h4><Link href={pathFor(locale,'/visit-us')+'#locations'}>Sunway 163 Mall</Link><br/><Link href={pathFor(locale,'/visit-us')+'#locations'}>SS2, Petaling Jaya</Link></div><div><h4>{c.common.hours}</h4><p>{c.common.hoursNote}</p></div><div><h4>{c.common.connected}</h4><a href="https://www.instagram.com/bibichikmy/" target="_blank" rel="noopener noreferrer">Instagram</a><br/><a href="https://www.facebook.com/BibiChikSdnBhd/" target="_blank" rel="noopener noreferrer">Facebook</a></div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} BiBiChik. {c.common.rights}</p><div><Link href={pathFor(locale,'/privacy')}>{c.common.privacy}</Link><Link href={pathFor(locale,'/terms')}>{c.common.terms}</Link></div></div><Motif className="footer-motif"/></footer>}
