"use client";
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useEffect,useState,type ReactNode} from 'react';
import {Menu} from 'lucide-react';
import {Sheet,SheetTrigger,SheetContent,SheetTitle,SheetDescription,SheetClose} from '@/components/ui/sheet';
const nav=[['Home','/'],['Our story','/our-story'],['Menu','/menu'],['Our flavours','/our-flavours'],['Visit us','/visit-us']];
export function Header(){const path=usePathname();const[scrolled,setScrolled]=useState(false);useEffect(()=>{const f=()=>setScrolled(window.scrollY>20);f();window.addEventListener('scroll',f,{passive:true});return()=>window.removeEventListener('scroll',f)},[]);return <header className={`site-header ${scrolled?'scrolled':''}`}><div className="header-inner"><Link className="brand" href="/" aria-label="BiBiChik home"><img src="/assets/logo.png" alt="BiBiChik — A Taste of Nyonya Heritage"/></Link><nav className="desktop-nav" aria-label="Main navigation">{nav.map(([n,h])=><Link href={h} key={h} aria-current={(h==='/'?path===h:path.startsWith(h))?'page':undefined}>{n}</Link>)}</nav><Button href="/visit-us#contact" className="booking">Book a table</Button><Sheet><SheetTrigger className="mobile-toggle" aria-label="Open navigation"><Menu/></SheetTrigger><SheetContent className="mobile-sheet"><SheetTitle>BiBiChik</SheetTitle><SheetDescription>A Taste of Nyonya Heritage</SheetDescription><nav aria-label="Mobile navigation">{nav.map(([n,h])=><SheetClose asChild key={h}><Link href={h}>{n}</Link></SheetClose>)}<SheetClose asChild><Link href="/visit-us#contact">Book a table</Link></SheetClose></nav></SheetContent></Sheet></div></header>}
export function Button({href,children,secondary=false,className=''}:{href:string,children:ReactNode,secondary?:boolean,className?:string}){return <Link className={`button ${secondary?'secondary':''} ${className}`} href={href}>{children}</Link>}
export function Motif({className=''}:{className?:string}){return <img className={`motif ${className}`} src="/assets/emblem.png" alt="" aria-hidden="true"/>}
export function Hero({title,subtitle,description,image,alt,children}:{title:ReactNode,subtitle:string,description?:string,image:string,alt:string,children?:ReactNode}){return <section className="hero container"><div className="hero-copy"><h1>{title}</h1><p className="hero-subtitle">{subtitle}</p>{description&&<p className="hero-description">{description}</p>}{children}</div><div className="hero-photo"><img src={`/assets/${image}.webp`} alt={alt} fetchPriority="high"/></div></section>}
const categories=[['Nyonya Classics','Rich, aromatic and full of character.','classics'],['Rice & Noodles','Comforting Malaysian favourites for any time of day.','noodles'],['Small Plates','A little bit of everything, best enjoyed together.','small-plates'],['Sweet Things','Classic Malaysian treats to finish the meal.','dessert'],['Drinks','Refreshing favourites inspired by local flavours.','drinks']];
export function MenuPreview(){return <section className="mint section"><div className="container"><div className="section-heading"><div><p className="eyebrow">A table full of favourites</p><h2>Our Menu</h2></div><Link className="text-link" href="/menu">View full menu <span>→</span></Link></div><div className="category-grid">{categories.map(([n,d,i])=><Link href="/menu" key={n} className="category"><img src={`/assets/${i}.webp`} alt={n} loading="lazy"/><h3>{n}</h3><p>{d}</p></Link>)}</div></div></section>}
export type Location={name:string,address:string,hours:string,phone:string,mapUrl:string,image:string};
export const locations:Location[]=[];
export function Locations({compact=false}:{compact?:boolean}){return <section className="blue section" id="locations"><div className="container"><div className="section-heading"><div><p className="eyebrow">Our locations</p><h2>Find Your Bibichik</h2></div><p>We can’t wait to welcome you.</p></div>{locations.length?<div className="location-grid">{locations.map(l=><article className="location-card" key={l.name}><img src={l.image} alt={l.name}/><div><h3>{l.name}</h3><p>{l.address}</p><p>{l.hours}</p><p>{l.phone}</p><a className="button secondary" href={l.mapUrl} target="_blank" rel="noopener noreferrer">Get directions</a></div></article>)}</div>:<div className={`location-pending ${compact?'compact':''}`}><img src="/assets/location-one.webp" alt="BiBiChik restaurant interior visual reference" loading="lazy"/><div><span className="eyebrow">Location details coming soon</span><h3>A warm welcome awaits.</h3><p>Our addresses, opening hours and contact details will be shared here once confirmed.</p><button className="button secondary" disabled>Get directions · Coming soon</button></div></div>}</div></section>}
export function Footer(){return <footer><div className="container footer-grid"><Link href="/" className="brand"><img src="/assets/logo.png" alt="BiBiChik — A Taste of Nyonya Heritage"/></Link><div><h4>Locations</h4><Link href="/visit-us">Find your Bibichik</Link><p>Details coming soon</p></div><div><h4>Opening hours</h4><p>To be confirmed</p></div><div><h4>Stay connected</h4><p>Instagram · Coming soon</p><p>Facebook · Coming soon</p></div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} BiBiChik. All rights reserved.</p><div><Link href="/privacy">Privacy Policy</Link><Link href="/terms">Terms & Conditions</Link></div></div><Motif className="footer-motif"/></footer>}
