export type Locale = 'en' | 'zh';

export const copy = {
  en: {
    nav: {home:'Home',story:'Our story',menu:'Menu',flavours:'Our flavours',visit:'Visit Us',open:'Open navigation',main:'Main navigation',mobile:'Mobile navigation'},
    common: {explore:'Explore our menu',story:'Our story',directions:'Get directions',reserve:'Reserve a table',locations:'Our locations',find:'Find Your Bibichik',welcome:'We can’t wait to welcome you.',hours:'Opening hours',closed:'Closed',connected:'Stay connected',hoursNote:'Check branch listings for current hours',rights:'All rights reserved.',privacy:'Privacy Policy',terms:'Terms & Conditions',skip:'Skip to content',table:'The Bibichik table'},
    home: {title:'A Taste of|Nyonya Heritage',subtitle:'Familiar flavours, lovingly made for today.',description:'Discover the warmth, colour and character of Malaysian Nyonya cuisine.',tag:'Truly|Malaysian|Flavours',eyebrow:'Truly Malaysian flavours',rootsTitle:'Rooted in Heritage,|Made for Today.',rootsBody:'At Bibichik, we celebrate Nyonya traditions and the flavours we grew up with — bringing familiar Malaysian favourites to the table with warmth, character and a little modern charm.',values:[['Recipes With Roots','Flavours inspired by generations of Nyonya cooking.'],['Made for Sharing','Food that belongs in the middle of the table.'],['A Malaysian Story','A celebration of the cultures, ingredients and flavours that make Malaysia home.']]},
    preview: {eyebrow:'A table full of favourites',title:'Our Menu',view:'View full menu',categories:[['Nyonya Classics','Rich, aromatic and full of character.'],['Rice & Noodles','Comforting Malaysian favourites for any time of day.'],['Small Plates','A little bit of everything, best enjoyed together.'],['Sweet Things','Classic Malaysian treats to finish the meal.'],['Drinks','Refreshing favourites inspired by local flavours.']]},
    story: {title:'Our Story',subtitle:'A celebration of Nyonya heritage, Malaysian flavours and the simple joy of good food.',beginning:'Our beginning',beginningTitle:'Rooted in Tradition,|Made for Today.',beginningBody:['Bibichik was born from a deep appreciation for Nyonya traditions and the vibrant flavours that have shaped Malaysian cuisine.','Inspired by the recipes, stories and home-cooked meals passed down through generations, we set out to bring these familiar tastes to the table in a space that feels warm, welcoming and contemporary.','At Bibichik, heritage is not just something we remember — it’s something we cook, share and keep alive every day.'],heritage:'Our heritage',heritageTitle:'A Unique Blend|of Cultures',heritageBody:['Nyonya cuisine is a beautiful meeting of Chinese and Malay influences, created over centuries in Malaysia.','It brings together aromatic spices, fresh herbs, rich ingredients and bold flavours — resulting in dishes that are colourful, comforting and truly one of a kind.'],cards:[['Rich flavours','Layers of spices and herbs create depth and character.'],['Cultural heritage','A blend of traditions that make Malaysian cuisine unique.'],['Timeless recipes','Classic flavours, prepared with care for today.']],space:'Our space',spaceTitle:'A Place|for Everyone',spaceBody:['More than just a restaurant, Bibichik is a place to gather — for family meals, casual catch-ups and new memories.','We’ve created a space that reflects our heritage while feeling fresh and welcoming.']},
    flavours: {title:'Our Flavours',subtitle:'A harmonious blend of heritage, culture and local ingredients that make Malaysian cuisine so unique.',table:'The Nyonya table',tableTitle:'A Rich|Culinary Heritage',tableBody:['Nyonya cuisine brings together Chinese and Malay influences, creating a distinctive Malaysian flavour profile that is rich, aromatic and full of character.','At Bibichik, we honour this unique heritage by staying true to traditional flavours while bringing them into a contemporary dining experience.'],define:'Flavours that define us',cards:[['Spice','Aromatic spices and herbs create layers of flavour and depth.'],['A Little Tang','Tamarind, lime and pickled flavours bring brightness to our dishes.'],['Something Sweet','Coconut, gula melaka and pandan add sweetness and balance.'],['Fresh Ingredients','Quality ingredients form the foundation of every dish.']],more:'More than just food',moreTitle:'A Malaysian|Experience',moreBody:['Our flavours tell a bigger story — one of diverse cultures, shared traditions and a deep love for good food.','Each dish reflects the vibrant, multicultural identity that makes Malaysia home.']},
    menu: {title:'Our Menu',choose:'Choose a menu to explore.',lunch:'Lunch Menu',dinner:'Dinner Menu',browse:'Browse {menu} menu',back:'Back to menu',original:'Original PDF',next:'Next',previous:'Previous',page:'Page',read:'Read page {page}',view:'View {menu}',swipe:'Swipe to turn the page. Tap “Read page” for a closer look.',click:'Click a page or use the arrow keys to turn.',dialog:'Original menu page. Scroll to read the full page.',endpaper:'A Taste of Nyonya Heritage'},
    visit: {title:'Visit Us',subtitle:'Come and experience the warmth of Nyonya flavours in a space made for everyone.',locationBody:'We can’t wait to welcome you. Dine with us at any of our locations and enjoy your Malaysian favourites in a warm and welcoming space.',touch:'Get in touch',touchTitle:'We’d Love to|Hear From You',touchBody:['Planning a gathering, celebration or simply have a question?','Drop us a message and we’ll get back to you soon.'],name:'Name',phone:'Phone',email:'Email',message:'Message',send:'Send message',unavailable:'Online enquiries are coming soon. A contact address has not yet been confirmed.',notSent:'Online enquiries are not available yet. Your message has not been sent.',emailOpen:'Your email app will open with your enquiry. Please send it there to complete your message.'},
    days:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],
    alt:{home:'Nyonya dishes in floral ceramics on a sunlit dining table',story:'Flowers in a ceramic vase beside books in warm window light',flavours:'Aromatic Nyonya chicken served in a floral ceramic bowl',visit:'Sunlit BiBiChik dining interior with rattan chairs and Nyonya details',table:'Friends sharing Nyonya dishes around the BiBiChik table',interior:'BiBiChik dining interior',contact:'A ceramic flower vase and BiBiChik menu',tiffin:'Floral Nyonya tiffin carrier and colourful kuih',tiles:'Peranakan floral ceramic tiles and Malaysian cookbooks',space:'A warm dining space with rattan chairs and marble tables',feast:'Nyonya dishes, kuih and drinks shared at the table'},
    meta:{description:'Discover the warmth, colour and character of Malaysian Nyonya cuisine. Explore our story, flavours and original lunch and dinner menus.'}
  },
  zh: {
    nav: {home:'首页',story:'品牌故事',menu:'菜单',flavours:'我们的风味',visit:'到访我们',open:'打开导航菜单',main:'主导航',mobile:'手机导航'},
    common: {explore:'探索菜单',story:'品牌故事',directions:'导航前往',reserve:'预订座位',locations:'我们的分店',find:'寻找 BiBiChik',welcome:'期待与你见面。',hours:'营业时间',closed:'休息',connected:'关注我们',hoursNote:'请查看各分店的最新营业时间',rights:'版权所有。',privacy:'隐私政策',terms:'条款与细则',skip:'跳转至主要内容',table:'BiBiChik 餐桌'},
    home: {title:'娘惹传统风味',subtitle:'熟悉的味道，以现代方式用心呈现。',description:'探索马来西亚娘惹料理的温度、色彩与独特风味。',tag:'真正的|马来西亚|风味',eyebrow:'真正的马来西亚风味',rootsTitle:'传承经典，|为今天而呈现。',rootsBody:'在 BiBiChik，我们珍惜娘惹传统与陪伴我们成长的熟悉味道，并以温暖、个性与现代感重新呈现经典马来西亚风味。',values:[['源自传承的食谱','灵感来自世代相传的娘惹料理。'],['为分享而生','适合摆在餐桌中央，与大家一起分享。'],['马来西亚的味道故事','以文化、食材与风味，呈现属于马来西亚的味道。']]},
    preview: {eyebrow:'一桌美味',title:'我们的菜单',view:'查看完整菜单',categories:[['娘惹经典','浓郁芳香，独具特色。'],['饭类与面食','随时都能享用的马来西亚经典美味。'],['小食','各式美味，最适合一起分享。'],['甜点','为一餐画上甜蜜句点的马来西亚经典甜品。'],['饮品','以本地风味为灵感的清爽饮品。']]},
    story: {title:'品牌故事',subtitle:'致敬娘惹文化、马来西亚风味，以及享受美食最简单的快乐。',beginning:'我们的起点',beginningTitle:'根植传统，|为今天而呈现。',beginningBody:['BiBiChik 源于我们对娘惹传统的热爱，以及对塑造马来西亚饮食文化的丰富风味的珍视。','受到世代相传的食谱、故事与家常料理启发，我们希望将这些熟悉的味道带到餐桌上，并以温暖、亲切且现代的方式呈现。','在 BiBiChik，传承不只是记忆，更是我们每天烹煮、分享，并持续延续的味道。'],heritage:'我们的传承',heritageTitle:'多元文化的|独特融合',heritageBody:['娘惹料理融合了华人与马来文化，并在马来西亚经过数百年的发展，形成独特的饮食风貌。','香料、香草、丰富食材与鲜明风味交织在一起，造就色彩丰富、令人熟悉又独具特色的料理。'],cards:[['丰富风味','香料与香草层层交叠，创造丰富而鲜明的味道。'],['文化传承','不同文化传统的融合，造就独特的马来西亚味道。'],['经典食谱','经典风味，用心为今天重新呈现。']],space:'我们的空间',spaceTitle:'属于每个人的|相聚空间',spaceBody:['BiBiChik 不只是一家餐厅，更是家人聚餐、朋友相聚与创造新回忆的地方。','我们打造了一个既保留文化特色，又轻松、现代且亲切的空间。']},
    flavours: {title:'我们的风味',subtitle:'传承、文化与本地食材交织，成就独特的马来西亚风味。',table:'娘惹餐桌',tableTitle:'深厚的|饮食传承',tableBody:['娘惹料理融合华人与马来文化，形成浓郁、芳香且极具个性的马来西亚风味。','在 BiBiChik，我们尊重传统味道，同时以现代餐饮体验重新呈现这份独特传承。'],define:'塑造我们味道的元素',cards:[['香料','芳香的香料与香草，让味道更有层次。'],['一点酸香','罗望子、青柠与腌渍风味，为料理增添清爽酸香。'],['一点甜味','椰香、椰糖与班兰带来自然甜味与平衡。'],['新鲜食材','优质食材，是每一道料理的基础。']],more:'不只是食物',moreTitle:'属于马来西亚的|味觉体验',moreBody:['我们的味道讲述着更大的故事——关于多元文化、共同传承，以及对美食的热爱。','每一道料理，都映照出马来西亚丰富而多元的文化特色。']},
    menu: {title:'我们的菜单',choose:'请选择菜单。',lunch:'午餐菜单',dinner:'晚餐菜单',browse:'浏览{menu}',back:'返回菜单',original:'原版 PDF',next:'下一页',previous:'上一页',page:'页',read:'阅读第 {page} 页',view:'查看{menu}',swipe:'左右滑动翻页。点击“阅读页面”可放大查看。',click:'点击页面或使用方向键翻页。',dialog:'原版菜单页面。请滚动查看完整内容。',endpaper:'娘惹传统风味'},
    visit: {title:'到访我们',subtitle:'来到 BiBiChik，在舒适的空间里感受娘惹料理的温度与风味。',locationBody:'期待你的到来。欢迎前往我们的分店，在温暖舒适的空间里享用熟悉的马来西亚风味。',touch:'联系我们',touchTitle:'欢迎与我们联系',touchBody:['无论是聚餐、庆祝活动，或只是想询问一些问题，都欢迎联系我们。','留下你的信息，我们会尽快回复。'],name:'姓名',phone:'电话',email:'电子邮箱',message:'留言',send:'发送留言',unavailable:'线上咨询即将开放。联系邮箱尚未确认。',notSent:'线上咨询暂未开放。你的留言尚未发送。',emailOpen:'邮件应用将打开并显示你的留言。请在邮件应用中发送，以完成留言。'},
    days:['星期一','星期二','星期三','星期四','星期五','星期六','星期日'],
    alt:{home:'阳光下的餐桌上，娘惹料理盛在花纹陶瓷餐具中',story:'温暖窗光中的花瓶与书本',flavours:'花纹陶瓷碗中的香浓娘惹鸡肉料理',visit:'阳光明亮的 BiBiChik 餐厅室内空间',table:'朋友们围坐分享娘惹料理',interior:'BiBiChik 餐厅室内',contact:'陶瓷花瓶与 BiBiChik 菜单',tiffin:'花纹娘惹提盒与缤纷糕点',tiles:'娘惹花纹瓷砖与马来西亚料理书',space:'藤椅与大理石桌面的温暖用餐空间',feast:'餐桌上共享的娘惹料理、糕点与饮品'},
    meta:{description:'探索马来西亚娘惹料理的温度、色彩与独特风味。了解 BiBiChik 的故事、风味及午餐与晚餐菜单。'}
  }
} as const;

export function pathFor(locale:Locale,path:string){return locale==='zh'?`/zh${path==='/'?'':path}`:path}
export function localeFromPath(path:string):Locale{return path==='/zh'||path.startsWith('/zh/')?'zh':'en'}
export function lines(value:string){return value.split('|')}
export function pageMetadata(locale:Locale,title:string,path:string){return {title,description:copy[locale].meta.description,alternates:{languages:{en:pathFor('en',path),'zh-CN':pathFor('zh',path)}}}}
